### ISSUE TITLE
I wonder how to add the sonar pulse

### ISSUE THREAD

**Issue by Vacancyy** [cs361fall2018/project-ggggggggggggroup-6#43]
I don't know how to add the sonar pulse in our project, please help me to figure out which files should I change ?

**Comment by FishPapa** [comment]
You need to write few functions in the java files and create some new files for the sonar. Also, on the front side, you need to create a new button and add listener for it in the Javascript file. Finally you need to connect the Java and Javascript together to make them work with each other properly.

**Comment by huangpujj** [comment]
First, you need a sonar class. then, you need to know what functions you need to implement. after you added features to the main folder. you need to change the application controller and router. then change your javascript to fit these functions
